CODE_OF_CONDUCT.md

created within a branch (instead of directly into main)

(re)created Code of Conduct file

---

age_prediction_analysis.qmd

accidentally forgot to move off this branch into another branch before editing results section! Sorry!

minor changes to analysis file

---

Dockerfile

worked on #69, changed docker version to a pinned version

edited dockerfile

---

.gitignore

worked on #70, ensured that .DS_Store file will no longer be committed to repo

edited gitignore file

---

.github/workflows/publish_docker_image.yml

related to #75 for Github Actions

PM2.1: edited workflow path of `.yml` file

---

README.md

- changed name of branch, as per #73 
- fixing `docker run` command instructions
- editing how to access the analysis, run the scripts (to do), and view the output (to do)
- testing github actions using new instructions

edited instructions on container image

---

README.md

added details to docker, adjusted formatting, added to-dos

---

scripts/04-analysis.R

edit to only load necessart libraries, adjusted to save both figures and tables, while using command-line arguments
#80 #76

abstract and use command-line arguments for 04-analysis.R

---

renv/.gitignore
renv/activate.R
renv/settings.json
scripts/04-analysis.R

fixed error when saving csv

---

scripts/02-data-clean-transform.R

#78
resolved error when running the `02-data-clean-transform.R` script because didn't have `readr` library for the `read_csv` function

added readr library

---

scripts/03-eda.R

edited 03-eda.R to take params

---

dsci-310-group-7-data-dudes.Rproj
renv.lock
renv/activate.R

fixed renv inconsistencies for script 1,2,4 (NOT 3 yet)

---

Makefile

corrected filepaths for 03-eda.R and 04-analysis.R

---

README.md

added dependency versions to readme

---

CONTRIBUTING.md
age_prediction_analysis.qmd

Made various fixes such as updating the contributing.md file to include more information, and lots of edits to the quarto analysis document related to formatting, image and table referencing, and bibliography referencing.
fixes #71
fixes #81
also ran reproducible analysis for #74

Quarto file and contributing.md update

---

R/data_cleaning.R
scripts/02-data-clean-transform.R
tests/testthat/test-data_cleaning.R

fixes #115 
fixes #119
Created 3 functions and 3 tests for the data cleaning file!

Create functions and tests for script #2 (data cleaning)

---

R/data_cleaning.R
R/eda_functions.R
scripts/02-data-clean-transform.R
scripts/03-eda.R
tests/testthat/test-data_cleaning.R
tests/testthat/test-eda.R

Adds to #124 
Adds to #123
Move functions to its own file for script 3, and also make some tests for script 3.

Add tests and move functions for script 3

---

R/create_directory.R
R/download_data.R
R/load_csv.R
tests/testthat/test-create_directory.R
tests/testthat/test-download_data.R
tests/testthat/test-load_csv.R

add back deleted 01 functions and tests

---

.gitignore
R/data_cleaning.R
scripts/02-data-clean-transform.R
scripts/03-eda.R
tests/testthat/test-data_cleaning.R
tests/testthat/test-eda.R

* Created thorough description for script 2 functions file (R/data_cleaning.R)
* Added library calls to test file
* updated .gitignore file
* used function taken from script 1 in script 2 file
* double checked script 3 info, and included a source to the load_csv file

Update script 2 testing and functions

---

data/clean/data-cleaned.csv
scripts/01-download-dataset.R
scripts/02-data-clean-transform.R
scripts/03-eda.R
scripts/04-analysis.R

* Began work for #149 by removing
* started removing use of load_csv() function
* Started #138 with my part of data validation checks, although having issues currently

Data validation and analysis repo updates

---

scripts/02-data-clean-transform.R

code validation: corrected to use data_transform instead of your_data in naz's code

---

scripts/02-data-clean-transform.R

Added two agents that checks for
(1) Correct category levels (i.e., no string mismatches or single values) 
(2) Target/response variable follows expected distribution

added jade's 2 validations

---

scripts/02-data-clean-transform.R
scripts/02.5-data-validation.R
scripts/04-analysis.R

fixes #138 by finishing all data validation in a single r script
adds to #149 by checking all scripts and making sure all functions and tests are now removed

Finish data validation

---

scripts/02.5-data-validation.R
scripts/04-analysis.R

Fixed @jadeeechen 's code to get `make all` to work

Small updates to validation and analysis for make 
